<?php

namespace App\Http\Helpers;

class DataHelper
{
    public $continent = array(
        'Asia'              =>  array('lat' => 23.7027273,'long' => 62.3750637 ),
        'North America'     =>  array('lat' => 31.6768272,'long' => -146.4707474 ),
        'South America'     =>  array('lat' => -15.6551563,'long' => -100.7484231 ),
        'Europe'            =>  array('lat' => 25.771324,'long' => -35.6012256),
        'Africa'            =>  array('lat' => 1.7383867,'long' => -16.3094636),
        'Australia/Oceania' =>  array('lat' => -8.6599161,'long' => 91.1469847)
    );

    public $contries = array(
        ['country' =>'Asia','iso2'=>null,'lat' => 23.7027273,'long' => 62.3750637 ],
        ['country' =>'North America','iso2'=>null,'lat' => 31.6768272,'long' => -146.4707474 ],
        ['country' =>'South America','iso2'=>null,'lat' => -15.6551563,'long' => -100.7484231 ],
        ['country' =>'Europe','iso2'=>null,'lat' => 25.771324,'long' => -35.6012256],
        ['country' =>'Africa','iso2'=>null,'lat' => 1.7383867,'long' => -16.3094636],
        ['country' =>'Australia/Oceania','iso2'=>null,'lat' => -8.6599161,'long' => 91.1469847],
        [ 'country' => 'Afghanistan', 'iso2' => 'AF', 'lat' => 33, 'long' => 65 ],
        [ 'country' => 'Albania', 'iso2' => 'AL', 'lat' => 41, 'long' => 20 ],
        [ 'country' => 'Algeria', 'iso2' => 'DZ', 'lat' => 28, 'long' => 3 ],
        [ 'country' => 'American Samoa', 'iso2' => 'AS', 'lat' => -14.3333, 'long' => -170 ],
        [ 'country' => 'Andorra', 'iso2' => 'AD', 'lat' => 42.5, 'long' => 1.6 ],
        [ 'country' => 'Angola', 'iso2' => 'AO', 'lat' => -12.5, 'long' => 18.5 ],
        [ 'country' => 'Anguilla', 'iso2' => 'AI', 'lat' => 18.25, 'long' => -63.1667 ],
        [ 'country' => 'Antarctica', 'iso2' => 'AQ', 'lat' => -90, 'long' => 0 ],
        [ 'country' => 'Antigua and Barbuda', 'iso2' => 'AG', 'lat' => 17.05, 'long' => -61.8 ],
        [ 'country' => 'Argentina', 'iso2' => 'AR', 'lat' => -34, 'long' => -64 ],
        [ 'country' => 'Armenia', 'iso2' => 'AM', 'lat' => 40, 'long' => 45 ],
        [ 'country' => 'Aruba', 'iso2' => 'AW', 'lat' => 12.5, 'long' => -69.9667 ],
        [ 'country' => 'Australia', 'iso2' => 'AU', 'lat' => -27, 'long' => 133 ],
        [ 'country' => 'Austria', 'iso2' => 'AT', 'lat' => 47.3333, 'long' => 13.3333 ],
        [ 'country' => 'Azerbaijan', 'iso2' => 'AZ', 'lat' => 40.5, 'long' => 47.5 ],
        [ 'country' => 'Bahamas', 'iso2' => 'BS', 'lat' => 24.25, 'long' => -76 ],
        [ 'country' => 'Bahrain', 'iso2' => 'BH', 'lat' => 26, 'long' => 50.55 ],
        [ 'country' => 'Bangladesh', 'iso2' => 'BD', 'lat' => 24, 'long' => 90 ],
        [ 'country' => 'Barbados', 'iso2' => 'BB', 'lat' => 13.1667, 'long' => -59.5333 ],
        [ 'country' => 'Belarus', 'iso2' => 'BY', 'lat' => 53, 'long' => 28 ],
        [ 'country' => 'Belgium', 'iso2' => 'BE', 'lat' => 50.8333, 'long' => 4 ],
        [ 'country' => 'Belize', 'iso2' => 'BZ', 'lat' => 17.25, 'long' => -88.75 ],
        [ 'country' => 'Benin', 'iso2' => 'BJ', 'lat' => 9.5, 'long' => 2.25 ],
        [ 'country' => 'Bermuda', 'iso2' => 'BM', 'lat' => 32.3333, 'long' => -64.75 ],
        [ 'country' => 'Bhutan', 'iso2' => 'BT', 'lat' => 27.5, 'long' => 90.5 ],
        [ 'country' => 'Bolivia', 'iso2' => 'BO', 'lat' => -17, 'long' => -65, 'possibleNames' => ['Bolivia, Plurinational State of'] ],
        [ 'country' => 'Bosnia', 'iso2' => 'BA', 'lat' => 44, 'long' => 18, 'possibleNames' => ['Bosnia and Herzegovina'] ],
        [ 'country' => 'Botswana', 'iso2' => 'BW', 'lat' => -22, 'long' => 24 ],
        [ 'country' => 'Bouvet Island', 'iso2' => 'BV', 'lat' => -54.4333, 'long' => 3.4 ],
        [ 'country' => 'Brazil', 'iso2' => 'BR', 'lat' => -10, 'long' => -55, 'possibleNames' => ['Brasil'] ],
        [ 'country' => 'British Indian Ocean Territory', 'iso2' => 'IO', 'lat' => -6, 'long' => 71.5 ],
        [ 'country' => 'Brunei', 'iso2' => 'BN', 'lat' => 4.5, 'long' => 114.6667, 'possibleNames' => ['Brunei Darussalam'] ],
        [ 'country' => 'Bulgaria', 'iso2' => 'BG', 'lat' => 43, 'long' => 25 ],
        [ 'country' => 'Burkina Faso', 'iso2' => 'BF', 'lat' => 13, 'long' => -2 ],
        [ 'country' => 'Burundi', 'iso2' => 'BI', 'lat' => -3.5, 'long' => 30 ],
        [ 'country' => 'Cabo Verde', 'iso2' => 'CV', 'lat' => 16, 'long' => -24, 'possibleNames' => ['Cape Verde'] ],
        [ 'country' => 'Cambodia', 'iso2' => 'KH', 'lat' => 13, 'long' => 105 ],
        [ 'country' => 'Cameroon', 'iso2' => 'CM', 'lat' => 6, 'long' => 12 ],
        [ 'country' => 'Canada', 'iso2' => 'CA', 'lat' => 60, 'long' => -95 ],
        [ 'country' => 'Cayman Islands', 'iso2' => 'KY', 'lat' => 19.5, 'long' => -80.5 ],
        [ 'country' => 'Central African Republic', 'iso2' => 'CF', 'lat' => 7, 'long' => 21, 'possibleNames' => ['CAR'] ],
        [ 'country' => 'Caribbean Netherlands', 'iso2' => 'BQ', 'lat' => 12.20, 'long' => -68.260, 'possibleNames' => ['Bonaire', 'San Eustaquio', 'Saba'] ],
        [ 'country' => 'Chad', 'iso2' => 'TD', 'lat' => 15, 'long' => 19 ],
        [ 'country' => 'Chile', 'iso2' => 'CL', 'lat' => -30, 'long' => -71 ],
        [ 'country' => 'China', 'iso2' => 'CN', 'lat' => 35, 'long' => 105 ],
        [ 'country' => 'Christmas Island', 'iso2' => 'CX', 'lat' => -10.5, 'long' => 105.6667 ],
        [ 'country' => 'Cocos (Keeling) Islands', 'iso2' => 'CC', 'lat' => -12.5, 'long' => 96.8333 ],
        [ 'country' => 'Colombia', 'iso2' => 'CO', 'lat' => 4, 'long' => -72 ],
        [ 'country' => 'Comoros', 'iso2' => 'KM', 'lat' => -12.1667, 'long' => 44.25 ],
        [ 'country' => 'Congo', 'iso2' => 'CG', 'lat' => -1, 'long' => 15, 'possibleNames' => ['Congo, Republic of', 'Congo (Brazzaville)'] ],
        [ 'country' => 'DRC', 'iso2' => 'CD', 'lat' => 0, 'long' => 25, 'possibleNames' => ['Congo, the Democratic Republic of the', 'Congo (Kinshasa)', 'Congo Kinshasa', 'Kinshasa'] ],
        [ 'country' => 'Cook Islands', 'iso2' => 'CK', 'lat' => -21.2333, 'long' => -159.7667 ],
        [ 'country' => 'Costa Rica', 'iso2' => 'CR', 'lat' => 10, 'long' => -84 ],
        [ 'country' => 'Côte d\'Ivoire', 'iso2' => 'CI', 'lat' => 8, 'long' => -5, 'possibleNames' => ['Ivory Coast', 'Coast D\'Ivoire'] ],
        [ 'country' => 'Croatia', 'iso2' => 'HR', 'lat' => 45.1667, 'long' => 15.5 ],
        [ 'country' => 'Cuba', 'iso2' => 'CU', 'lat' => 21.5, 'long' => -80 ],
        [ 'country' => 'Curaçao', 'iso2' => 'CW', 'lat' => 12.15, 'long' => -68.97, 'possibleNames' => ['Curazao', 'Curacao'] ],
        [ 'country' => 'Cyprus', 'iso2' => 'CY', 'lat' => 35, 'long' => 33 ],
        [ 'country' => 'Czechia', 'iso2' => 'CZ', 'lat' => 49.75, 'long' => 15.5, 'possibleNames' => ['Czech Republic', 'Chequia'] ],
        [ 'country' => 'Denmark', 'iso2' => 'DK', 'lat' => 56, 'long' => 10 ],
        [ 'country' => 'Djibouti', 'iso2' => 'DJ', 'lat' => 11.5, 'long' => 43 ],
        [ 'country' => 'Dominica', 'iso2' => 'DM', 'lat' => 15.4167, 'long' => -61.3333 ],
        [ 'country' => 'Dominican Republic', 'iso2' => 'DO', 'lat' => 19, 'long' => -70.6667, 'possibleNames' => ['DR'] ],
        [ 'country' => 'Ecuador', 'iso2' => 'EC', 'lat' => -2, 'long' => -77.5 ],
        [ 'country' => 'Egypt', 'iso2' => 'EG', 'lat' => 27, 'long' => 30 ],
        [ 'country' => 'El Salvador', 'iso2' => 'SV', 'lat' => 13.8333, 'long' => -88.9167 ],
        [ 'country' => 'Equatorial Guinea', 'iso2' => 'GQ', 'lat' => 2, 'long' => 10 ],
        [ 'country' => 'Eritrea', 'iso2' => 'ER', 'lat' => 15, 'long' => 39 ],
        [ 'country' => 'Estonia', 'iso2' => 'EE', 'lat' => 59, 'long' => 26 ],
        [ 'country' => 'Ethiopia', 'iso2' => 'ET', 'lat' => 8, 'long' => 38 ],
        [ 'country' => 'Falkland Islands (Malvinas)', 'iso2' => 'FK', 'lat' => -51.75, 'long' => -59, 'possibleNames' => ['Falkland Islands', 'Malvinas'] ],
        [ 'country' => 'Faroe Islands', 'iso2' => 'FO', 'lat' => 62, 'long' => -7, 'possibleNames' => ['Faeroe Islands'] ],
        [ 'country' => 'Fiji', 'iso2' => 'FJ', 'lat' => -18, 'long' => 175 ],
        [ 'country' => 'Finland', 'iso2' => 'FI', 'lat' => 64, 'long' => 26 ],
        [ 'country' => 'France', 'iso2' => 'FR', 'lat' => 46, 'long' => 2 ],
        [ 'country' => 'French Guiana', 'iso2' => 'GF', 'lat' => 4, 'long' => -53 ],
        [ 'country' => 'French Polynesia', 'iso2' => 'PF', 'lat' => -15, 'long' => -140 ],
        [ 'country' => 'French Southern Territories', 'iso2' => 'TF', 'lat' => -43, 'long' => 67 ],
        [ 'country' => 'Gabon', 'iso2' => 'GA', 'lat' => -1, 'long' => 11.75 ],
        [ 'country' => 'Gambia', 'iso2' => 'GM', 'lat' => 13.4667, 'long' => -16.5667 ],
        [ 'country' => 'Georgia', 'iso2' => 'GE', 'lat' => 42, 'long' => 43.5 ],
        [ 'country' => 'Germany', 'iso2' => 'DE', 'lat' => 51, 'long' => 9 ],
        [ 'country' => 'Ghana', 'iso2' => 'GH', 'lat' => 8, 'long' => -2 ],
        [ 'country' => 'Gibraltar', 'iso2' => 'GI', 'lat' => 36.1833, 'long' => -5.3667 ],
        [ 'country' => 'Greece', 'iso2' => 'GR', 'lat' => 39, 'long' => 22 ],
        [ 'country' => 'Greenland', 'iso2' => 'GL', 'lat' => 72, 'long' => -40 ],
        [ 'country' => 'Grenada', 'iso2' => 'GD', 'lat' => 12.1167, 'long' => -61.6667 ],
        [ 'country' => 'Guadeloupe', 'iso2' => 'GP', 'lat' => 16.25, 'long' => -61.5833 ],
        [ 'country' => 'Guam', 'iso2' => 'GU', 'lat' => 13.4667, 'long' => 144.7833 ],
        [ 'country' => 'Guatemala', 'iso2' => 'GT', 'lat' => 15.5, 'long' => -90.25 ],
        [ 'country' => 'Guernsey', 'iso2' => 'GG', 'lat' => 49.5, 'long' => -2.56 ],
        [ 'country' => 'Guinea', 'iso2' => 'GN', 'lat' => 11, 'long' => -10 ],
        [ 'country' => 'Guinea-Bissau', 'iso2' => 'GW', 'lat' => 12, 'long' => -15 ],
        [ 'country' => 'Guyana', 'iso2' => 'GY', 'lat' => 5, 'long' => -59 ],
        [ 'country' => 'Haiti', 'iso2' => 'HT', 'lat' => 19, 'long' => -72.4167 ],
        [ 'country' => 'Heard Island and McDonald Islands', 'iso2' => 'HM', 'lat' => -53.1, 'long' => 72.5167 ],
        [ 'country' => 'Holy See (Vatican City State)', 'iso2' => 'VA', 'lat' => 41.9, 'long' => 12.45, 'possibleNames' => ['Vatican City'] ],
        [ 'country' => 'Honduras', 'iso2' => 'HN', 'lat' => 15, 'long' => -86.5 ],
        [ 'country' => 'Hong Kong', 'iso2' => 'HK', 'lat' => 22.25, 'long' => 114.1667 ],
        [ 'country' => 'Hungary', 'iso2' => 'HU', 'lat' => 47, 'long' => 20 ],
        [ 'country' => 'Iceland', 'iso2' => 'IS', 'lat' => 65, 'long' => -18 ],
        [ 'country' => 'India', 'iso2' => 'IN', 'lat' => 20, 'long' => 77 ],
        [ 'country' => 'Indonesia', 'iso2' => 'ID', 'lat' => -5, 'long' => 120 ],
        [ 'country' => 'Iran', 'iso2' => 'IR', 'lat' => 32, 'long' => 53, 'possibleNames' => ['Iran, Islamic Republic of'] ],
        [ 'country' => 'Iraq', 'iso2' => 'IQ', 'lat' => 33, 'long' => 44 ],
        [ 'country' => 'Ireland', 'iso2' => 'IE', 'lat' => 53, 'long' => -8 ],
        [ 'country' => 'Isle of Man', 'iso2' => 'IM', 'lat' => 54.23, 'long' => -4.55 ],
        [ 'country' => 'Israel', 'iso2' => 'IL', 'lat' => 31.5, 'long' => 34.75 ],
        [ 'country' => 'Italy', 'iso2' => 'IT', 'lat' => 42.8333, 'long' => 12.8333, 'possibleNames' => ['Italia'] ],
        [ 'country' => 'Jamaica', 'iso2' => 'JM', 'lat' => 18.25, 'long' => -77.5 ],
        [ 'country' => 'Japan', 'iso2' => 'JP', 'lat' => 36, 'long' => 138, 'possibleNames' => ['Japón'] ],
        [ 'country' => 'Channel Islands', 'iso2' => 'JE', 'lat' => 49.21, 'long' => -2.13, 'possibleNames' => ['Jersey', 'Guernsey'] ],
        [ 'country' => 'Jordan', 'iso2' => 'JO', 'lat' => 31, 'long' => 36 ],
        [ 'country' => 'Kazakhstan', 'iso2' => 'KZ', 'lat' => 48, 'long' => 68 ],
        [ 'country' => 'Kenya', 'iso2' => 'KE', 'lat' => 1, 'long' => 38 ],
        [ 'country' => 'Kiribati', 'iso2' => 'KI', 'lat' => 1.4167, 'long' => 173 ],
        [ 'country' => 'Kosovo', 'iso2' => 'XK', 'lat' => 42.6, 'long' => 20.9 ],
        [ 'country' => 'N. Korea', 'iso2' => 'KP', 'lat' => 40, 'long' => 127, 'possibleNames' => ['Korea del Norte', 'North Korea', 'Korea, North', 'Democratic People\'s Republic of Korea'] ],
        [ 'country' => 'S. Korea', 'iso2' => 'KR', 'lat' => 37, 'long' => 127.5, 'possibleNames' => ['Korea del Sur', 'South Korea', 'Korea, South', 'Republic of Korea'] ],
        [ 'country' => 'Kuwait', 'iso2' => 'KW', 'lat' => 29.3375, 'long' => 47.6581 ],
        [ 'country' => 'Kyrgyzstan', 'iso2' => 'KG', 'lat' => 41, 'long' => 75 ],
        [ 'country' => 'Lao People\'s Democratic Republic', 'iso2' => 'LA', 'lat' => 18, 'long' => 105, 'possibleNames' => ['Laos'] ],
        [ 'country' => 'Latvia', 'iso2' => 'LV', 'lat' => 57, 'long' => 25 ],
        [ 'country' => 'Lebanon', 'iso2' => 'LB', 'lat' => 33.8333, 'long' => 35.8333 ],
        [ 'country' => 'Lesotho', 'iso2' => 'LS', 'lat' => -29.5, 'long' => 28.5 ],
        [ 'country' => 'Liberia', 'iso2' => 'LR', 'lat' => 6.5, 'long' => -9.5 ],
        [ 'country' => 'Libyan Arab Jamahiriya', 'iso2' => 'LY', 'lat' => 25, 'long' => 17, 'possibleNames' => ['Libya', 'Libia'] ],
        [ 'country' => 'Liechtenstein', 'iso2' => 'LI', 'lat' => 47.1667, 'long' => 9.5333 ],
        [ 'country' => 'Lithuania', 'iso2' => 'LT', 'lat' => 56, 'long' => 24 ],
        [ 'country' => 'Luxembourg', 'iso2' => 'LU', 'lat' => 49.75, 'long' => 6.1667 ],
        [ 'country' => 'Macao', 'iso2' => 'MO', 'lat' => 22.1667, 'long' => 113.55, 'possibleNames' => ['Macao', 'macau'] ],
        [ 'country' => 'Macedonia', 'iso2' => 'MK', 'lat' => 41.8333, 'long' => 22, 'possibleNames' => ['North Macedonia', 'Macedonia, the former Yugoslav Republic of'] ],
        [ 'country' => 'Madagascar', 'iso2' => 'MG', 'lat' => -20, 'long' => 47 ],
        [ 'country' => 'Malawi', 'iso2' => 'MW', 'lat' => -13.5, 'long' => 34 ],
        [ 'country' => 'Malaysia', 'iso2' => 'MY', 'lat' => 2.5, 'long' => 112.5 ],
        [ 'country' => 'Maldives', 'iso2' => 'MV', 'lat' => 3.25, 'long' => 73 ],
        [ 'country' => 'Mali', 'iso2' => 'ML', 'lat' => 17, 'long' => -4 ],
        [ 'country' => 'Malta', 'iso2' => 'MT', 'lat' => 35.8333, 'long' => 14.5833 ],
        [ 'country' => 'Marshall Islands', 'iso2' => 'MH', 'lat' => 9, 'long' => 168 ],
        [ 'country' => 'Martinique', 'iso2' => 'MQ', 'lat' => 14.6667, 'long' => -61 ],
        [ 'country' => 'Mauritania', 'iso2' => 'MR', 'lat' => 20, 'long' => -12 ],
        [ 'country' => 'Mauritius', 'iso2' => 'MU', 'lat' => -20.2833, 'long' => 57.55 ],
        [ 'country' => 'Mayotte', 'iso2' => 'YT', 'lat' => -12.8333, 'long' => 45.1667 ],
        [ 'country' => 'Mexico', 'iso2' => 'MX', 'lat' => 23, 'long' => -102 ],
        [ 'country' => 'Micronesia', 'iso2' => 'FM', 'lat' => 6.9167, 'long' => 158.25, 'possibleNames' => ['Micronesia, Federated States of'] ],
        [ 'country' => 'Moldova', 'iso2' => 'MD', 'lat' => 47, 'long' => 29, 'possibleNames' => ['Moldova, Republic of'] ],
        [ 'country' => 'Monaco', 'iso2' => 'MC', 'lat' => 43.7333, 'long' => 7.4 ],
        [ 'country' => 'Mongolia', 'iso2' => 'MN', 'lat' => 46, 'long' => 105 ],
        [ 'country' => 'Montenegro', 'iso2' => 'ME', 'lat' => 42, 'long' => 19 ],
        [ 'country' => 'Montserrat', 'iso2' => 'MS', 'lat' => 16.75, 'long' => -62.2 ],
        [ 'country' => 'Morocco', 'iso2' => 'MA', 'lat' => 32, 'long' => -5 ],
        [ 'country' => 'Mozambique', 'iso2' => 'MZ', 'lat' => -18.25, 'long' => 35 ],
        [ 'country' => 'Myanmar', 'iso2' => 'MM', 'lat' => 22, 'long' => 98 ],
        [ 'country' => 'Burma', 'iso2' => 'BU', 'lat' => 22, 'long' => 98 ],
        [ 'country' => 'Namibia', 'iso2' => 'NA', 'lat' => -22, 'long' => 17 ],
        [ 'country' => 'Nauru', 'iso2' => 'NR', 'lat' => -0.5333, 'long' => 166.9167 ],
        [ 'country' => 'Nepal', 'iso2' => 'NP', 'lat' => 28, 'long' => 84 ],
        [ 'country' => 'Netherlands', 'iso2' => 'NL', 'lat' => 52.5, 'long' => 5.75 ],
        [ 'country' => 'Netherlands Antilles', 'iso2' => 'AN', 'lat' => 12.25, 'long' => -68.75 ],
        [ 'country' => 'New Caledonia', 'iso2' => 'NC', 'lat' => -21.5, 'long' => 165.5 ],
        [ 'country' => 'New Zealand', 'iso2' => 'NZ', 'lat' => -41, 'long' => 174 ],
        [ 'country' => 'Nicaragua', 'iso2' => 'NI', 'lat' => 13, 'long' => -85 ],
        [ 'country' => 'Niger', 'iso2' => 'NE', 'lat' => 16, 'long' => 8 ],
        [ 'country' => 'Nigeria', 'iso2' => 'NG', 'lat' => 10, 'long' => 8 ],
        [ 'country' => 'Niue', 'iso2' => 'NU', 'lat' => -19.0333, 'long' => -169.8667 ],
        [ 'country' => 'Norfolk Island', 'iso2' => 'NF', 'lat' => -29.0333, 'long' => 167.95 ],
        [ 'country' => 'Northern Mariana Islands', 'iso2' => 'MP', 'lat' => 15.2, 'long' => 145.75 ],
        [ 'country' => 'Norway', 'iso2' => 'NO', 'lat' => 62, 'long' => 10 ],
        [ 'country' => 'Oman', 'iso2' => 'OM', 'lat' => 21, 'long' => 57 ],
        [ 'country' => 'Pakistan', 'iso2' => 'PK', 'lat' => 30, 'long' => 70 ],
        [ 'country' => 'Palau', 'iso2' => 'PW', 'lat' => 7.5, 'long' => 134.5 ],
        [ 'country' => 'Palestine', 'iso2' => 'PS', 'lat' => 32, 'long' => 35.25, 'possibleNames' => ['Palestinian Territory, Occupied'] ],
        [ 'country' => 'Panama', 'iso2' => 'PA', 'lat' => 9, 'long' => -80 ],
        [ 'country' => 'Papua New Guinea', 'iso2' => 'PG', 'lat' => -6, 'long' => 147 ],
        [ 'country' => 'Paraguay', 'iso2' => 'PY', 'lat' => -23, 'long' => -58 ],
        [ 'country' => 'Peru', 'iso2' => 'PE', 'lat' => -10, 'long' => -76 ],
        [ 'country' => 'Philippines', 'iso2' => 'PH', 'lat' => 13, 'long' => 122 ],
        [ 'country' => 'Pitcairn', 'iso2' => 'PN', 'lat' => -24.7, 'long' => -127.4 ],
        [ 'country' => 'Poland', 'iso2' => 'PL', 'lat' => 52, 'long' => 20 ],
        [ 'country' => 'Portugal', 'iso2' => 'PT', 'lat' => 39.5, 'long' => -8 ],
        [ 'country' => 'Puerto Rico', 'iso2' => 'PR', 'lat' => 18.25, 'long' => -66.5 ],
        [ 'country' => 'Qatar', 'iso2' => 'QA', 'lat' => 25.5, 'long' => 51.25 ],
        [ 'country' => 'Réunion', 'iso2' => 'RE', 'lat' => -21.1, 'long' => 55.6, 'possibleNames' => ['Reunion'] ],
        [ 'country' => 'Romania', 'iso2' => 'RO', 'lat' => 46, 'long' => 25 ],
        [ 'country' => 'Russia', 'iso2' => 'RU', 'lat' => 60, 'long' => 100, 'possibleNames' => ['Russian Federation'] ],
        [ 'country' => 'Rwanda', 'iso2' => 'RW', 'lat' => -2, 'long' => 30 ],
        [ 'country' => 'St. Barth', 'iso2' => 'BL', 'lat' => 17.89, 'long' => -62.82 ],
        [ 'country' => 'Saint Helena', 'iso2' => 'SH', 'lat' => -15.9333, 'long' => -5.7, 'possibleNames' => ['Saint Helena, Ascension and Tristan da Cunha'] ],
        [ 'country' => 'Saint Kitts and Nevis', 'iso2' => 'KN', 'lat' => 17.3333, 'long' => -62.75 ],
        [ 'country' => 'Saint Lucia', 'iso2' => 'LC', 'lat' => 13.8833, 'long' => -61.1333 ],
        [ 'country' => 'Saint Pierre Miquelon', 'iso2' => 'PM', 'lat' => 46.8333, 'long' => -56.3333, 'possibleNames' => ['Saint Pierre and Miquelon'] ],
        [ 'country' => 'Saint Martin', 'iso2' => 'MF', 'lat' => 18.11, 'long' => -63.03, 'possibleNames' => ['St. Martin', 'St Martin'] ],
        [ 'country' => 'Sint Maarten', 'iso2' => 'SX', 'lat' => 18.02, 'long' => -63.06 ],
        [ 'country' => 'Saint Vincent and the Grenadines', 'iso2' => 'VC', 'lat' => 13.25, 'long' => -61.2, 'possibleNames' => ['Saint Vincent & the Grenadines', 'St. Vincent and the Grenadines', 'St. Vincent Grenadines'] ],
        [ 'country' => 'Samoa', 'iso2' => 'WS', 'lat' => -13.5833, 'long' => -172.3333 ],
        [ 'country' => 'San Marino', 'iso2' => 'SM', 'lat' => 43.7667, 'long' => 12.4167 ],
        [ 'country' => 'Sao Tome and Principe', 'iso2' => 'ST', 'lat' => 1, 'long' => 7 ],
        [ 'country' => 'Saudi Arabia', 'iso2' => 'SA', 'lat' => 25, 'long' => 45 ],
        [ 'country' => 'Senegal', 'iso2' => 'SN', 'lat' => 14, 'long' => -14 ],
        [ 'country' => 'Serbia', 'iso2' => 'RS', 'lat' => 44, 'long' => 21 ],
        [ 'country' => 'Seychelles', 'iso2' => 'SC', 'lat' => -4.5833, 'long' => 55.6667 ],
        [ 'country' => 'Sierra Leone', 'iso2' => 'SL', 'lat' => 8.5, 'long' => -11.5 ],
        [ 'country' => 'Singapore', 'iso2' => 'SG', 'lat' => 1.3667, 'long' => 103.8 ],
        [ 'country' => 'Slovakia', 'iso2' => 'SK', 'lat' => 48.6667, 'long' => 19.5 ],
        [ 'country' => 'Slovenia', 'iso2' => 'SI', 'lat' => 46, 'long' => 15 ],
        [ 'country' => 'Solomon Islands', 'iso2' => 'SB', 'lat' => -8, 'long' => 159 ],
        [ 'country' => 'Somalia', 'iso2' => 'SO', 'lat' => 10, 'long' => 49 ],
        [ 'country' => 'South Africa', 'iso2' => 'ZA', 'lat' => -29, 'long' => 24 ],
        [ 'country' => 'South Georgia and the South Sandwich Islands', 'iso2' => 'GS', 'lat' => -54.5, 'long' => -37 ],
        [ 'country' => 'South Sudan', 'iso2' => 'SS', 'lat' => 6.8769, 'long' => 31.3069 ],
        [ 'country' => 'Spain', 'iso2' => 'ES', 'lat' => 40, 'long' => -4, 'possibleNames' => ['España'] ],
        [ 'country' => 'Sri Lanka', 'iso2' => 'LK', 'lat' => 7, 'long' => 81 ],
        [ 'country' => 'Sudan', 'iso2' => 'SD', 'lat' => 15, 'long' => 30 ],
        [ 'country' => 'Suriname', 'iso2' => 'SR', 'lat' => 4, 'long' => -56 ],
        [ 'country' => 'Svalbard and Jan Mayen', 'iso2' => 'SJ', 'lat' => 78, 'long' => 20 ],
        [ 'country' => 'Swaziland', 'iso2' => 'SZ', 'lat' => -26.5, 'long' => 31.5, 'possibleNames' => ['Esuatini', 'Eswatini'] ],
        [ 'country' => 'Sweden', 'iso2' => 'SE', 'lat' => 62, 'long' => 15 ],
        [ 'country' => 'Switzerland', 'iso2' => 'CH', 'lat' => 47, 'long' => 8 ],
        [ 'country' => 'Syrian Arab Republic', 'iso2' => 'SY', 'lat' => 35, 'long' => 38, 'possibleNames' => ['Syria'] ],
        [ 'country' => 'Taiwan', 'iso2' => 'TW', 'lat' => 23.5, 'long' => 121, 'possibleNames' => ['Taiwan, Province of China'] ],
        [ 'country' => 'Tajikistan', 'iso2' => 'TJ', 'lat' => 39, 'long' => 71 ],
        [ 'country' => 'Tanzania', 'iso2' => 'TZ', 'lat' => -6, 'long' => 35, 'possibleNames' => ['Tanzania, United Republic of'] ],
        [ 'country' => 'Thailand', 'iso2' => 'TH', 'lat' => 15, 'long' => 100 ],
        [ 'country' => 'Timor-Leste', 'iso2' => 'TL', 'lat' => -8.55, 'long' => 125.5167 ],
        [ 'country' => 'Togo', 'iso2' => 'TG', 'lat' => 8, 'long' => 1.1667 ],
        [ 'country' => 'Tokelau', 'iso2' => 'TK', 'lat' => -9, 'long' => -172 ],
        [ 'country' => 'Tonga', 'iso2' => 'TO', 'lat' => -20, 'long' => -175 ],
        [ 'country' => 'Trinidad and Tobago', 'iso2' => 'TT', 'lat' => 11, 'long' => -61, 'possibleNames' => ['Triniad & Tobago'] ],
        [ 'country' => 'Tunisia', 'iso2' => 'TN', 'lat' => 34, 'long' => 9 ],
        [ 'country' => 'Turkey', 'iso2' => 'TR', 'lat' => 39, 'long' => 35 ],
        [ 'country' => 'Turkmenistan', 'iso2' => 'TM', 'lat' => 40, 'long' => 60 ],
        [ 'country' => 'Turks and Caicos Islands', 'iso2' => 'TC', 'lat' => 21.75, 'long' => -71.5833, 'possibleNames' => ['Turks and Caicos'] ],
        [ 'country' => 'Tuvalu', 'iso2' => 'TV', 'lat' => -8, 'long' => 178 ],
        [ 'country' => 'Uganda', 'iso2' => 'UG', 'lat' => 1, 'long' => 32 ],
        [ 'country' => 'Ukraine', 'iso2' => 'UA', 'lat' => 49, 'long' => 32 ],
        [ 'country' => 'UAE', 'iso2' => 'AE', 'lat' => 24, 'long' => 54, 'possibleNames' => ['United Arab Emirates'] ],
        [ 'country' => 'UK', 'iso2' => 'GB', 'lat' => 54, 'long' => -2, 'possibleNames' => ['England', 'United Kingdom'] ],
        [ 'country' => 'USA', 'iso2' => 'US', 'lat' => 38, 'long' => -97, 'possibleNames' => ['USA', 'America', 'Estados Unidos', 'United States of America', 'United States'] ],
        [ 'country' => 'United States Minor Outlying Islands', 'iso2' => 'UM', 'lat' => 19.2833, 'long' => 166.6 ],
        [ 'country' => 'Uruguay', 'iso2' => 'UY', 'lat' => -33, 'long' => -56 ],
        [ 'country' => 'Uzbekistan', 'iso2' => 'UZ', 'lat' => 41, 'long' => 64 ],
        [ 'country' => 'Vanuatu', 'iso2' => 'VU', 'lat' => -16, 'long' => 167 ],
        [ 'country' => 'Venezuela', 'iso2' => 'VE', 'lat' => 8, 'long' => -66, 'possibleNames' => ['Venezuela, Bolivarian Republic of'] ],
        [ 'country' => 'Vietnam', 'iso2' => 'VN', 'lat' => 21, 'long' => 105.8, 'possibleNames' => ['Viet Nam'] ],
        [ 'country' => 'British Virgin Islands', 'iso2' => 'VG', 'lat' => 18.5, 'long' => -64.5, 'possibleNames' => ['Virgin Islands, British'] ],
        [ 'country' => 'U.S. Virgin Islands', 'iso2' => 'VI', 'lat' => 18.3333, 'long' => -64.8333, 'possibleNames' => ['Virgin Islands'] ],
        [ 'country' => 'Wallis and Futuna', 'iso2' => 'WF', 'lat' => -13.3, 'long' => -176.2 ],
        [ 'country' => 'Western Sahara', 'iso2' => 'EH', 'lat' => 24.5, 'long' => -13 ],
        [ 'country' => 'Yemen', 'iso2' => 'YE', 'lat' => 15, 'long' => 48 ],
        [ 'country' => 'Zambia', 'iso2' => 'ZM', 'lat' => -15, 'long' => 30 ],
        [ 'country' => 'Zimbabwe', 'iso2' => 'ZW', 'lat' => -20, 'long' => 30 ]
    );
}
